version: '3.8'

services:
  elasticsearch:
    image: dh-mirror.gitverse.ru/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solo-leveling-container
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  esdata:

networks:
  elastic: