server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 604800
logging:
  level:
    org:
      atmosphere: warn
spring:
  mustache:
    check-template-location: false
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: false
vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.example.application
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}