server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 604800
logging:
  level:
    org:
      atmosphere: warn
spring:
  mustache:
    check-template-location: false
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: ${ELASTICSEARCH_HOST}  # Указываем адрес Elasticsearch
      repositories:
        enabled: true  # Включаем репозитории Elasticsearch
      rest:
        uris: http://${ELASTICSEARCH_HOST}  # Указываем URI для REST-клиента
vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.example.application
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}