server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 604800
logging:
  level:
    org:
      atmosphere: warn
spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:postgresql://${SERVER_HOST}:5432/solo_leveling
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        transaction:
          jta:
            platform: none
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: false
vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.example.application
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}